# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples_tsv: "/scratch/07467/jwr2735/rna-seq/snakemake/config/samples.tsv"
fastq_dir: "/scratch/07467/jwr2735/rna-seq/fastq/"
star_genome: "/scratch/07467/jwr2735/rna-seq/star-ref/"
